### ISSUE TITLE
Fail to remove reference if stored node contains reference meta-pointer with empty targets

### ISSUE THREAD

**Issue by enikao** [LionWeb-io/lionweb-repository#18] opened 2024-01-19 16:19 UTC
Assume the repository contains [Disk_A.json](https://github.com/LionWeb-io/lionweb-repository/files/13991595/Disk_A.json).

When we `store` [Disk-move-child-partition.json](https://github.com/LionWeb-io/lionweb-repository/files/13991599/Disk-move-child-partition.json), we expect node `ID-4` to have no references. It actually keeps the reference to `ID-10`.

**Comment by joswarmer** [comment] 2024-01-21 11:11
Hi, I tried this on main branch, but I cannot reproduce the problem.

**Comment by joswarmer** [comment] 2024-01-23 11:04
Looked at it with Niko, cannot reproduce it together either, so closing this.

**Comment by enikao** [comment] 2024-01-24 19:56
I think this issue still exists.

Use branch [lw-java/bulk-api](https://github.com/LionWeb-io/lionweb-java/tree/niko/bulk-api) and execute test [`TestRemoveReference.updateSingleNode()`](https://github.com/LionWeb-io/lionweb-java/blob/7cda7a8c479e25cb14eb08dbea268bdddb530c39/bulk-api/src/test/java/io/lionweb/api/bulk/test/store/TestRemoveReference.java#L15)

Expected:
```
SerializedClassifierInstance{id='ID-4', parentNodeID='ID-3',
...
 references=SerializedReferenceValue{metaPointer=MetaPointer{key='Folder-linked-key', version='2023.1', language='-default-key-FileSystem'}, value=[Entry{resolveInfo='null', reference='ID-10'}, Entry{resolveInfo='null', reference='ID-8'}]},
...
```

actual:
```
SerializedClassifierInstance{id='ID-4', parentNodeID='ID-3',
...
 references=SerializedReferenceValue{metaPointer=MetaPointer{key='Folder-linked-key', version='2023.1', language='-default-key-FileSystem'}, value=[]},
...
```

Somehow opposite in `TestChangePropertyValue.updateNode3()`:

expected:
```
SerializedClassifierInstance{id='ID-4', parentNodeID='ID-3',
...
 references=SerializedReferenceValue{metaPointer=MetaPointer{key='Folder-linked-key', version='2023.1', language='-default-key-FileSystem'}, value=[]},
...
```

actual:
```
SerializedClassifierInstance{id='ID-4', parentNodeID='ID-3',
...
 references=SerializedReferenceValue{metaPointer=MetaPointer{key='Folder-linked-key', version='2023.1', language='-default-key-FileSystem'}, value=[Entry{resolveInfo='null', reference='ID-10'}, Entry{resolveInfo='null', reference='ID-8'}]},
...
```

**Comment by joswarmer** [comment] 2024-01-25 16:55
I cannot run the Java code, building the project fails.  What I do see is that the file `Disk-remove-reference-partition.json` you are using is actually the same as Disk_A.json, the references are still in the file. That is not how it was intended, but the expected result might then be different.

**Comment by enikao** [comment] 2024-01-26 14:39
I copied the json files from lw-repo/main. Now `TestRemoveReference` works, but still one issue with `TestChangePropertyValue.updateNode3()`:

expected:
```
SerializedClassifierInstance{id='ID-4', parentNodeID='ID-3',
...
 references=,
...
```

actual:
```
SerializedClassifierInstance{id='ID-4', parentNodeID='ID-3',
...
 references=SerializedReferenceValue{metaPointer=MetaPointer{key='Folder-linked-key', version='2023.1', language='-default-key-FileSystem'}, value=[Entry{resolveInfo='null', reference='ID-10'}, Entry{resolveInfo='null', reference='ID-8'}]},
...
```

**Comment by joswarmer** [comment] 2024-01-28 14:25
This seens to be correct, because the two references are in `DIsk_A` , and applying `Disk_Property_value_changed-single-node.json` does not remove them. Theese two references are missing in the `Disk_Property_value_changed-partition` json.

**Comment by enikao** [comment] 2024-01-28 19:05
Did I introduce this issue during translation to Java or is the TS test missing the discrepancy?

**Comment by joswarmer** [comment] 2024-01-29 11:08
In general the TS testcases check whether the retrieve is identical to the **partition**.json in the same folder, so this kind of discrepancy will not be found.  
In this specific case the references are in the **partition**.json, so they have probably been changed after you copied them.

In the `@lionweb/typescript` repo we use the testcases from `https://github.com/LionWeb-io/lionweb-integration-testing` . These tests are not copied, but are checked out in a setup script. Although they are not automatically updated, it is easy to do a git clean + project setup to update them. Maybe such a setup would make it easier to keep things synchronized.

**Comment by joswarmer** [comment] 2024-06-19 10:00
Closing because cannot reproduce it

**Closed by joswarmer** 2024-06-19 10:00 UTC
