### ISSUE TITLE
Repository object is not rendered conveniently in log messages

### ISSUE THREAD

**Issue by ftomassetti** [LionWeb-io/lionweb-repository#65] opened 2024-06-25 06:02 UTC
In the console output, I saw this string:
```
query:  SET search_path TO "repository:[object Object]";
```

We may need to check how the repository object is printed in log messages.

**Comment by joswarmer** [comment] 2024-06-25 08:37
This seems to be more important than just a console message. The `[object Object]` should be a string, and it isn't. Most probably because the request to the server is lacking the repository parameter.  This is an error that should be caught.  

Do you have the request data?

**Comment by ftomassetti** [comment] 2024-06-25 11:47
> Do you have the request data?

No, sorry, I noticed it in the output but I did a ton of requests so I do not know which request caused this, but the problem could be here: https://github.com/LionWeb-io/lionweb-repository/blob/058780d5b29d5857d98bc2658eaea4fc5f9cc777/packages/common/src/database/DbConnection.ts#L19

**Comment by joswarmer** [comment] 2024-07-03 07:18
This should be fixed by now, but since I could not reproduce it, lets keep an eye open for this happening again (or not).

**Comment by joswarmer** [comment] 2024-07-17 19:08
Closing, because cannot reproduce it.  Please re-open if it occurs again.

**Closed by joswarmer** 2024-07-17 19:08 UTC
